server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: payments-service


integration:
  product:
    url: "http://localhost:8080/api/v1/product"
    get-products-by-user-path: "/search"
    update-balance-path: "/{id}/update-balance"